package io.github.chronosauros.contour.core.native

import io.github.chronosauros.contour.core.FilterType
import kotlin.math.sqrt

/** Source rules are evidence, not transport authorisation or hardware support claims. */
data class FiioCaptureIdentity(val vendorId: Int, val productId: Int, val productName: String, val fixturePath: String)
data class FiioConfig(
    val productName: String,
    val vendorIds: Set<Int>,
    val reportId: Int,
    val maxFilters: Int,
    val minGainDb: Double,
    val maxGainDb: Double,
    val minQ: Double,
    val maxQ: Double,
    val saveCommand: Int,
    val userSlots: Set<Int>,
    val declaredWritableSlots: Set<Int>,
    val stockSlots: Set<Int>,
    val slotLabels: Map<Int, String>,
    val bypassSlot: Int?,
    val disconnectOnSave: Boolean,
    val peakingGainCompensation: Boolean,
    val shelfAlphaCompensation: Boolean,
    val sourceUrl: String,
    val constraintsUrl: String,
    val constraintsRef: String,
    val upstreamExperimental: Boolean,
    val bestGuessProductName: Boolean,
    val capture: FiioCaptureIdentity?,
    val codecBlockers: List<String>,
    val evidenceCaveats: List<String>,
    val status: String = "beta-unverified",
    // Only source handler's actual types: PK=0, LSQ=1, HSQ=2. JSON advertises
    // more types but no supported writer/decoder exists; do not use those codes.
    val typeCodes: Map<FilterType, Int> = mapOf(FilterType.PEAK to 0, FilterType.LOW_SHELF to 1, FilterType.HIGH_SHELF to 2),
    // Conservative source connector input range, not an acoustic/firmware guarantee.
    val minFrequencyHz: Int = 20,
    val maxFrequencyHz: Int = 20000,
    // Hardware-observed (KA15, 03.10.2026): the DAC ignores a lower filter count and keeps reading back
    // maxFilters, so the unused tail must be written as neutral filters instead of shortening the count.
    val fixedBandCount: Boolean = false,
    // Hardware-observed: stored Q reads back 1-2 hundredths higher for Q above ~3.5 (390 -> 391, 605 -> 607).
    val qReadbackSlack: Boolean = false,
    // KA15 echoes every AA write; reading each echo keeps request and reply in lockstep.
    val consumeWriteEchoes: Boolean = false,
    // Pause after every AA write, for DACs that do not echo writes (consumeWriteEchoes paces the KA15 instead).
    val writeGapMs: Int = 0,
    // Official web app (fiiocontrol.fiio.com, captured 03.10.2026): byte 3 = host sequence, byte before EE =
    // CRC-8/MAXIM over header..data. The device also answers zeros, so this is fidelity, not a requirement.
    val checksumFrames: Boolean = false,
    // Hardware-observed (KA15 on Android, 03.10.2026): HID replies stop while no USB audio is streaming;
    // the app keeps a silent output track on the DAC for the whole HID session.
    val needsAudioStream: Boolean = false,
    // Official web app (KA15 capture, 03.10.2026): command 0x30 reads and writes the USER slot names,
    // index = position in the sorted userSlots (USER1 = 0).
    val userSlotNames: Boolean = false,
    // Lets the user choose a USER slot without FiiO name commands; enable per device after a hardware test.
    val userSlotPicker: Boolean = false,
    // Hardware-measured (KA15, 04.10.2026, line-in sweeps against Close EQ): LS/HS shelves play Q = register / sqrt(2)
    // for every type, frequency, gain and Q, so the register holds intended Q * shelfQScale. PK Q is played as stored.
    // Not combinable with shelfAlphaCompensation (the devicePEQ slope law measured wrong on the KA15).
    val shelfQScale: Double = 1.0,
    // Hardware-measured (KA15, 04.10.2026): with any USER preset active, output = input - 12 dB + preamp register,
    // so the register holds intended preamp + preampOffsetDb.
    val preampOffsetDb: Double = 0.0,
) {
    /** Intended (acoustic) preamp range: the register range minus [preampOffsetDb]. */
    val preampMinDb: Double get() = minGainDb - preampOffsetDb
    val preampMaxDb: Double get() = maxGainDb - preampOffsetDb
    /** Intended (acoustic) shelf Q range: the register Q range divided by [shelfQScale]. */
    val shelfQMin: Double get() = minQ / shelfQScale
    val shelfQMax: Double get() = maxQ / shelfQScale
    val hardwareGates: List<String> get() = listOf(
        "Verify exact USB identity and HID interface/descriptor/report size before I/O",
        "Verify selection, complete backup, post-save native readback on actual firmware",
        "Persistence across power cycle and acoustic behaviour unverified",
    )
}

object FiioCatalog {
    const val PINNED_COMMIT = "0617f382e76629792a5933e6933e4b396a756a93"
    const val SOURCE_ROOT = "https://github.com/jeromeof/devicePEQ/blob/$PINNED_COMMIT/"
    const val HANDLER_SOURCE = "${SOURCE_ROOT}devicePEQ/fiioUsbHidHandler.js"
    const val FREQUENCY_RANGE_SOURCE = "${SOURCE_ROOT}devicePEQ/usbHidConnector.js#L221"

    /** Exact literal rules, no normalisation, wildcard product names, or VID-only fallback.
     * userSlots = declared writable range INTERSECT labelled USER ids MINUS stock/bypass.
     * In KA17-style conflicting maps only 8/9 survive; neither stock 7 nor out-of-range 4.
     */
    val rules: List<FiioConfig> = listOf(
        FiioConfig(
            productName = "FIIO QX13",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6, 8),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 8 to "Retro", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10", 240 to "BYPASS"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = true,
            shelfAlphaCompensation = true,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L69",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = FiioCaptureIdentity(10610, 296, "FIIO QX13", "tests/captures/fiio_fiio_qx13.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Source peaking rbjGain compensation enabled; actual firmware/acoustics unverified", "Source shelf peakingAlpha enabled; gain/Q dependence is a source prediction, not full measurement evidence"),
        ),
        FiioConfig(
            productName = "SNOWSKY Melody",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162),
            declaredWritableSlots = setOf(160, 161, 162),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 240 to "Close EQ"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L102",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = FiioCaptureIdentity(10610, 294, "SNOWSKY Melody", "tests/captures/fiio_snowsky_melody.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Fixture comment claims -24/+12; authoritative resolved constraints remain -12/+12"),
        ),
        FiioConfig(
            productName = "JadeAudio JIEZI",
            vendorIds = setOf(10610, 2578),
            reportId = 2,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162),
            declaredWritableSlots = setOf(160, 161, 162),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 240 to "Close EQ"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L118",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1167",
            constraintsRef = "peq5Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "JadeAudio JA11",
            vendorIds = setOf(10610, 2578),
            reportId = 2,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(3),
            declaredWritableSlots = setOf(3),
            stockSlots = setOf(1),
            slotLabels = mapOf(0 to "Vocal", 1 to "Classic", 2 to "Bass", 3 to "USER1"),
            bypassSlot = 4,
            disconnectOnSave = true,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L142",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L4",
            constraintsRef = "peq5Band12dBFullShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = FiioCaptureIdentity(10610, 258, "JadeAudio JA11", "tests/captures/fiio_jadeaudio_ja11.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf(),
        ),
        FiioConfig(
            productName = "FIIO KA17",
            vendorIds = setOf(10610, 2578),
            reportId = 1,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "BYPASS"),
            bypassSlot = 10,
            disconnectOnSave = false,
            peakingGainCompensation = true,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L156",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = FiioCaptureIdentity(10610, 147, "FIIO KA17", "tests/captures/fiio_fiio_ka17.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "Source peaking rbjGain compensation enabled; actual firmware/acoustics unverified"),
        ),
        FiioConfig(
            productName = "FIIO Q7",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "BYPASS"),
            bypassSlot = 10,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L173",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO KA17 (MQA HID)",
            vendorIds = setOf(10610, 2578),
            reportId = 1,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "BYPASS"),
            bypassSlot = 10,
            disconnectOnSave = false,
            peakingGainCompensation = true,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L189",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "No known capture PID; exact source name/vendor is informational only, not an automatic route", "Source peaking rbjGain compensation enabled; actual firmware/acoustics unverified"),
        ),
        FiioConfig(
            productName = "FIIO BT11",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3"),
            bypassSlot = 11,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L206",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO BT11 (UAC1.0)",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3"),
            bypassSlot = 11,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L221",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO Air Link",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 5, 6, 7),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 5 to "R&B", 6 to "Classic", 7 to "Hip-hop", 4 to "USER1", 8 to "USER2", 9 to "USER3"),
            bypassSlot = 11,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L236",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Slot conflict: stock 7 forbidden; USER1=4 outside writable 7..9; only 8/9 allowed", "No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO BTR13",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(7, 8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 7 to "USER1", 8 to "USER2", 9 to "USER3", 11 to "Close EQ"),
            bypassSlot = 11,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L251",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO BTR17",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 33,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10", 240 to "BYPASS"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L266",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1087",
            constraintsRef = "peq10Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "BTR17",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 33,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10", 240 to "BYPASS"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L285",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1087",
            constraintsRef = "peq10Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO K19",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 31,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 33,
            userSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            declaredWritableSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Rock", 2 to "R&B", 3 to "Hip-hop", 4 to "Pop", 5 to "Dance", 6 to "Classic", 7 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "USER4", 11 to "USER5", 12 to "USER6", 13 to "USER7", 14 to "USER8", 15 to "USER9", 16 to "USER10", 17 to "Close EQ"),
            bypassSlot = 17,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L304",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1060",
            constraintsRef = "peq31Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO K17",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 31,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 33,
            userSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            declaredWritableSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Rock", 2 to "R&B", 3 to "Hip-hop", 4 to "Pop", 5 to "Dance", 6 to "Classic", 7 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "USER4", 11 to "USER5", 12 to "USER6", 13 to "USER7", 14 to "USER8", 15 to "USER9", 16 to "USER10", 17 to "Close EQ"),
            bypassSlot = 17,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L323",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1060",
            constraintsRef = "peq31Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO K15",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            declaredWritableSlots = setOf(7, 8, 9, 10, 11, 12, 13, 14, 15, 16),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 7 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "USER4", 11 to "USER5", 12 to "USER6", 13 to "USER7", 14 to "USER8", 15 to "USER9", 16 to "USER10", 240 to "BYPASS"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L342",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO KA15",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(7, 8, 9),
            declaredWritableSlots = setOf(7, 8, 9),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 7 to "USER1", 8 to "USER2", 9 to "USER3", 10 to "Close EQ"),
            bypassSlot = 10,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L360",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = FiioCaptureIdentity(10610, 260, "FIIO KA15", "tests/captures/fiio_fiio_ka15.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Explicit FiiO route for exact FIIO KA15 2972:0104; ignore upstream WalkPlay-SchemeNo10 collision"),
            fixedBandCount = true,
            qReadbackSlack = true,
            consumeWriteEchoes = true,
            checksumFrames = true,
            needsAudioStream = true,
            userSlotNames = true,
            // Measured 04.10.2026 (research/protocol/PROTOCOL.md, FiiO KA15): shelf Q register = Q * sqrt(2),
            // preamp register = preamp + 12 dB. Intended ranges: shelf Q up to 10 / sqrt(2), preamp -24..0 dB.
            shelfQScale = sqrt(2.0),
            preampOffsetDb = 12.0,
        ),
        FiioConfig(
            productName = "FIIO K13 R2R",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6, 8),
            slotLabels = mapOf(240 to "BYPASS", 0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 8 to "Retro", 9 to "sDamp-1", 10 to "sDamp-2", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L375",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
            userSlotPicker = true,
            // Hardware 10.10.2026 (Pixel): a COUNT write of 9 read back 10 and band 10 kept its old registers. Without
            // the neutral pad a shorter profile would leave the slot's previous band 10 active and audible.
            fixedBandCount = true,
            // Hardware 10.10.2026: writes 16 ms apart all read back, but after a power cycle only the first one to three
            // survived (USER10: band 1; USER9: preamp and bands 1-2), the rest reverted. 300 ms per write: all kept.
            writeGapMs = 300,
        ),
        FiioConfig(
            productName = "FIIO BR15 R2R",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6, 8),
            slotLabels = mapOf(240 to "BYPASS", 0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 8 to "Retro", 9 to "sDamp-1", 10 to "sDamp-2", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L407",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1117",
            constraintsRef = "peq10Band12dBWideLSHP",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO FP3",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160),
            declaredWritableSlots = setOf(160),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L439",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1087",
            constraintsRef = "peq10Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "SNOWSKY TINY A",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162),
            declaredWritableSlots = setOf(160, 161, 162),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 240 to "Close EQ"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L457",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1167",
            constraintsRef = "peq5Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "SNOWSKY TINY B",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162),
            declaredWritableSlots = setOf(160, 161, 162),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 240 to "Close EQ"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L481",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1167",
            constraintsRef = "peq5Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO FG3",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 12 to "Cinema", 13 to "FPS", 14 to "MOBA", 15 to "ACT", 16 to "MUG", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L505",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1142",
            constraintsRef = "peq10Band12dBAllFiltersBP",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO LS-TC2",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160),
            declaredWritableSlots = setOf(160),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L537",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L4",
            constraintsRef = "peq5Band12dBFullShelves",
            upstreamExperimental = true,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
        FiioConfig(
            productName = "FIIO OAK NANO",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160),
            declaredWritableSlots = setOf(160),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L558",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1087",
            constraintsRef = "peq10Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = true,
            capture = FiioCaptureIdentity(10610, 16406, "FIIO OAK NANO", "tests/captures/fiio_fiio_oak_nano.json"),
            codecBlockers = listOf(),
            evidenceCaveats = listOf("Captured active count 8 does not lower declared maxFilters=10; asynchronous duplicate/misassociated RX must be correlated", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "Oak Nano",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160),
            declaredWritableSlots = setOf(160),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L572",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1087",
            constraintsRef = "peq10Band12dBWideShelves",
            upstreamExperimental = false,
            bestGuessProductName = true,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "RETRO NANO",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162),
            declaredWritableSlots = setOf(160, 161, 162),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6, 8),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 8 to "Retro", 9 to "sDamp-1", 10 to "sDamp-2", 160 to "USER1", 161 to "USER2", 162 to "USER3", 11 to "Close EQ"),
            bypassSlot = 11,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L587",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = true,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "FIIO QX11",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6, 8),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 8 to "Retro", 9 to "sDamp-1", 10 to "sDamp-2", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L606",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L1029",
            constraintsRef = "peq10Band12dBAllFilters7",
            upstreamExperimental = false,
            bestGuessProductName = true,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "FIIO AIR AMP",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 7 to "Monitor", 9 to "sDamp-1", 10 to "sDamp-2", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10", 240 to "BYPASS"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L625",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = true,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "FIIO DM15 R2R",
            vendorIds = setOf(10610, 2578),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(),
            declaredWritableSlots = setOf(160, 161, 162, 163, 164, 165, 166, 167, 168, 169),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(240 to "BYPASS", 0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1", 161 to "USER2", 162 to "USER3", 163 to "USER4", 164 to "USER5", 165 to "USER6", 166 to "USER7", 167 to "USER8", 168 to "USER9", 169 to "USER10"),
            bypassSlot = 240,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L645",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = true,
            bestGuessProductName = true,
            capture = null,
            codecBlockers = listOf("FZ=-1: source suspects CDC/serial; standard HID transport unproven"),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "USB product name explicitly best-guess in upstream configuration"),
        ),
        FiioConfig(
            productName = "FIIO FX17",
            vendorIds = setOf(260, 283, 285, 1633, 1635, 1638, 1890, 2313, 3468, 12230, 13058, 13502, 13784, 13991, 14139, 24769, 24801, 46149, 46157),
            reportId = 7,
            maxFilters = 10,
            minGainDb = -24.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(160),
            declaredWritableSlots = setOf(160),
            stockSlots = setOf(0, 1, 2, 3, 4, 5, 6),
            slotLabels = mapOf(0 to "Jazz", 1 to "Pop", 2 to "Rock", 3 to "Dance", 4 to "R&B", 5 to "Classic", 6 to "Hip-hop", 160 to "USER1"),
            bypassSlot = null,
            disconnectOnSave = false,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L803",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L994",
            constraintsRef = "peq10Band12dBWideAllFilters",
            upstreamExperimental = false,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf(),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route", "Source lacks explicit reportId; handler fallback is 7, descriptor/tester confirmation required"),
        ),
        FiioConfig(
            productName = "Space Gaming IEM",
            vendorIds = setOf(12722),
            reportId = 2,
            maxFilters = 5,
            minGainDb = -12.0,
            maxGainDb = 12.0,
            minQ = 0.1,
            maxQ = 10.0,
            saveCommand = 25,
            userSlots = setOf(),
            declaredWritableSlots = setOf(3),
            stockSlots = setOf(1),
            slotLabels = mapOf(0 to "Vocal", 1 to "Classic", 2 to "Bass", 3 to "USER1"),
            bypassSlot = 4,
            disconnectOnSave = true,
            peakingGainCompensation = false,
            shelfAlphaCompensation = false,
            sourceUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/usbDeviceConfig.js#L1126",
            constraintsUrl = "https://github.com/jeromeof/devicePEQ/blob/0617f382e76629792a5933e6933e4b396a756a93/devicePEQ/peqConstraintsConfig.json#L4",
            constraintsRef = "peq5Band12dBFullShelves",
            upstreamExperimental = true,
            bestGuessProductName = false,
            capture = null,
            codecBlockers = listOf("Excluded: unknown FiiO-vs-KT firmware/compensate2X policy; no proven capture/identity"),
            evidenceCaveats = listOf("No known capture PID; exact source name/vendor is informational only, not an automatic route"),
        ),
    )

    /** Informational source lookup only: does not authorize opening an arbitrary HID. */
    fun sourceRule(vendorId: Int, productName: String): FiioConfig? =
        rules.singleOrNull { productName == it.productName && vendorId in it.vendorIds }

    /** Positive route solely for six captured exact VID/PID/name identities; descriptor still
     * required. In particular KA15 2972:0104 routes here, not upstream WalkPlay fallback.
     * Qudelix shared VID and every unknown PID/name return null; no probing writes.
     */
    fun capturedRoute(vendorId: Int, productId: Int, productName: String): FiioConfig? =
        rules.singleOrNull { rule ->
            rule.codecBlockers.isEmpty() && rule.capture?.let {
                it.vendorId == vendorId && it.productId == productId && it.productName == productName
            } == true
        }
}
